const BOLT_FUN_LIGHTNING_ADDRESS = 'johns@getalby.com' // #TODO, replace it by bolt-fun lightning address if there exist one
const JWT_SECRET = process.env.JWT_SECRET
const LNURL_AUTH_HOST = process.env.LNURL_AUTH_HOST
const LNURL_AUTH_HOST_V2 = process.env.LNURL_AUTH_HOST_V2
const CLOUDFLARE_IMAGE_ACCOUNT_ID = process.env.CLOUDFLARE_IMAGE_ACCOUNT_ID
const CLOUDFLARE_IMAGE_API_KEY = process.env.CLOUDFLARE_IMAGE_API_KEY
const CLOUDFLARE_IMAGE_ACCOUNT_HASH = process.env.CLOUDFLARE_IMAGE_ACCOUNT_HASH

const CONSTS = {
    JWT_SECRET,
    BOLT_FUN_LIGHTNING_ADDRESS,
    LNURL_AUTH_HOST,
    LNURL_AUTH_HOST_V2,
    CLOUDFLARE_IMAGE_ACCOUNT_ID,
    CLOUDFLARE_IMAGE_API_KEY,
    CLOUDFLARE_IMAGE_ACCOUNT_HASH
}

module.exports = CONSTS
