const BOLT_FUN_LIGHTNING_ADDRESS = "johns@getalby.com"; // #TODO, replace it by bolt-fun lightning address if there exist one
const JWT_SECRET = process.env.JWT_SECRET;
const LNURL_AUTH_HOST = process.env.LNURL_AUTH_HOST;
const CLOUDFLARE_IMAGE_ACCOUNT_ID = process.env.CLOUDFLARE_IMAGE_ACCOUNT_ID;
const CLOUDFLARE_IMAGE_API_KEY = process.env.CLOUDFLARE_IMAGE_API_KEY;
const CLOUDFLARE_IMAGE_ACCOUNT_HASH = process.env.CLOUDFLARE_IMAGE_ACCOUNT_HASH;
const DISCORD_NOTIFICATIONS_WEBHOOK_URL =
  process.env.DISCORD_NOTIFICATIONS_WEBHOOK_URL;

const CONSTS = {
  JWT_SECRET,
  BOLT_FUN_LIGHTNING_ADDRESS,
  LNURL_AUTH_HOST,
  CLOUDFLARE_IMAGE_ACCOUNT_ID,
  CLOUDFLARE_IMAGE_API_KEY,
  CLOUDFLARE_IMAGE_ACCOUNT_HASH,
  DISCORD_NOTIFICATIONS_WEBHOOK_URL,
};

module.exports = CONSTS;
